# Generated by Django 4.1.4 on 2022-12-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect4',
            name='user2_choice',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='connect4',
            name='user1_choice',
            field=models.IntegerField(default=1),
        ),
    ]
