# Generated by Django 4.1.4 on 2022-12-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0002_connect4_user2_choice_alter_connect4_user1_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect4',
            name='z7',
            field=models.IntegerField(default=0),
        ),
    ]
