# Generated by Django 4.1.4 on 2022-12-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0005_connect4_game_name_connect4_user1_turn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect4',
            name='z1',
        ),
        migrations.RemoveField(
            model_name='connect4',
            name='z2',
        ),
        migrations.RemoveField(
            model_name='connect4',
            name='z3',
        ),
        migrations.RemoveField(
            model_name='connect4',
            name='z4',
        ),
        migrations.RemoveField(
            model_name='connect4',
            name='z5',
        ),
        migrations.RemoveField(
            model_name='connect4',
            name='z6',
        ),
        migrations.RemoveField(
            model_name='connect4',
            name='z7',
        ),
    ]
