# Generated by Django 4.1.4 on 2023-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0006_remove_connect4_z1_remove_connect4_z2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect4',
            name='user1_choice',
        ),
        migrations.RemoveField(
            model_name='connect4',
            name='user2_choice',
        ),
        migrations.AddField(
            model_name='connect4',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
